#ifndef __COLORS_16BIT_H
#define __COLORS_16BIT_H

#define BLACK                   0x0000
#define NAVY                    0x0010
#define DARK_BLUE               0x0011
#define MEDIUM_BLUE             0x0019
#define BLUE                    0x001F
#define DARK_GREEN              0x0320
#define GREEN_W3C               0x0400
#define TEAL                    0x0410
#define DARK_CYAN               0x0451
#define DEEP_SKY_BLUE           0x05FF
#define DARK_TURQUOISE          0x067A
#define MEDIUM_SPRING_GREEN     0x07D3
#define GREEN                   0x07E0
#define LIME_W3C                0x07E0
#define SPRING_GREEN            0x07EF
#define AQUA                    0x07FF
#define CYAN                    0x07FF
#define MIDNIGHT_BLUE           0x18CE
#define DODGER_BLUE             0x1C9F
#define FOREST_GREEN            0x2444
#define LIGHT_SEA_GREEN         0x2595
#define DARK_SLATE_GRAY         0x2A69
#define SEA_GREEN               0x2C4A
#define LIME_GREEN              0x3666
#define MEDIUM_SEA_GREEN        0x3D8E
#define ROYAL_BLUE              0x435C
#define STEEL_BLUE              0x4416
#define TURQUOISE               0x471A
#define INDIGO                  0x4810
#define DARK_SLATE_BLUE         0x49F1
#define MEDIUM_TURQUOISE        0x4E99
#define DARK_OLIVE_GREEN        0x5345
#define CADET_BLUE              0x5CF4
#define CORNFLOWER              0x64BD
#define MEDIUM_AQUAMARINE       0x6675
#define SLATE_BLUE              0x6AD9
#define DIM_GRAY                0x6B4D
#define OLIVE_DRAB              0x6C64
#define SLATE_GRAY              0x6AD9
#define LIGHT_SLATE_GRAY        0x7453
#define MAROON_W3C              0x7800
#define PURPLE_W3C              0x780F
#define MEDIUM_SLATE_BLUE       0x7B5D
#define CHARTREUSE              0x7FE0
#define LAWN_GREEN              0x7FE0
#define AQUAMARINE              0x7FFA
#define OLIVE                   0x8400
#define GRAY_W3C                0x8410
#define SKY_BLUE                0x867D
#define LIGHT_SKY_BLUE          0x867F
#define DARK_RED                0x8800
#define DARK_MAGENTA            0x8811
#define BLUE_VIOLET             0x895C
#define SADDLE_BROWN            0x8A22
#define DARK_SEA_GREEN          0x8DF1
#define DARK_VIOLET             0x901A
#define MEDIUM_PURPLE           0x939B
#define LIGHT_GREEN             0x9772
#define DARK_ORCHID             0x9999
#define YELLOW_GREEN            0x9E66
#define PALE_GREEN              0x9FD3
#define PURPLE_X11              0xA11E
#define BROWN                   0xA145
#define SIENNA                  0xA285
#define DARK_GRAY               0xAD55
#define LIGHT_BLUE              0xAEDC
#define PALE_TURQUOISE          0xAF7D
#define GREEN_YELLOW            0xAFE5
#define FIREBRICK               0xB104
#define MAROON_X11              0xB18C
#define LIGHT_STEEL_BLUE        0xB63B
#define POWDER_BLUE             0xB71C
#define MEDIUM_ORCHID           0xBABA
#define DARK_GOLDENROD          0xBC21
#define ROSY_BROWN              0xBC71
#define DARK_KHAKI              0xBDAD
#define GRAY_X11                0xBDF7
#define MEDIUM_VIOLET_RED       0xC0B0
#define SILVER_W3C              0xC618
#define INDIAN_RED              0xCAEB
#define PERU                    0xCC27
#define CHOCOLATE               0xD343
#define TAN                     0xD5B1
#define LIGHT_GRAY              0xD69A
#define CRIMSON                 0xD8A7
#define PALE_VIOLET_RED         0xDB92
#define ORCHID                  0xDB9A
#define PLUM                    0xDD1B
#define GOLDENROD               0xDD24
#define BURLYWOOD               0xDDD0
#define THISTLE                 0xDDFB
#define GAINSBORO               0xDEFB
#define LAVENDER                0xE73F
#define LIGHT_CYAN              0xE7FF
#define VIOLET                  0xEC1D
#define DARK_SALMON             0xECAF
#define PALE_GOLDENROD          0xEF55
#define LIGHT_CORAL             0xF410
#define SANDY_BROWN             0xF52C
#define WHEAT                   0xF6F6
#define KHAKI                   0xF731
#define BEIGE                   0xF7B9
#define WHITE_SMOKE             0xF7BE
#define ALICE_BLUE              0xF7DF
#define HONEYDEW                0xF7FE
#define AZURE                   0xF7FF
#define MINT_CREAM              0xF7FF
#define RED                     0xF800
#define FUCHSIA                 0xF81F
#define MAGENTA                 0xF81F
#define DEEP_PINK               0xF8B2
#define ORANGE_RED              0xFA20
#define TOMATO                  0xFB08
#define HOT_PINK                0xFB56
#define CORAL                   0xFBEA
#define SALMON                  0xFC0E
#define DARK_ORANGE             0xFC60
#define LIGHT_SALMON            0xFD0F
#define ORANGE                  0xFBE0
#define LIGHT_PINK              0xFE19
#define PINK                    0xFDB8
#define GOLD                    0xFEA8
#define PEACH_PUFF              0xFED7
#define NAVAJO_WHITE            0xFEF5
#define MOCCASIN                0xFF36
#define BISQUE                  0xFF38
#define MISTY_ROSE              0xFF3C
#define BLANCHED_ALMOND         0xFF59
#define ANTIQUE_WHITE           0xFF5A
#define PAPAYA_WHIP             0xFF7A
#define LINEN                   0xFF9C
#define LAVENDER_BLUSH          0xFF9E
#define OLD_LACE                0xFFBC
#define SEAHSELL                0xFFBD
#define LEMON_CHIFFON           0xFFD9
#define LIGHT_GOLDENROD         0xFFDA
#define CORNSILK                0xFFDB
#define FLORAL_WHITE            0xFFDE
#define GHOST_WHITE             0xFFDF
#define SNOW                    0xFFDF
#define YELLOW                  0xFFE0
#define LIGHT_YELLOW            0xFFFC
#define IVORY                   0xFFFE
#define WHITE                   0xFFFF
#endif
